+++
title = "CWE-248: Uncaught Exception"
description	= "An exception is thrown from a function, but it is not caught."
weight = 248

[extra]
id = 248
name = "Uncaught Exception"
url = "https://cwe.mitre.org/data/definitions/248.html"
vote = "Virtually Impossible"
clippy_helps = false
rust_docs_links = [
	
]
+++
One of the big selling-points of Rust safety - they take a hard line on exceptions
